export const ACTION_FORM_GET = 'ACTION_FORM_GET'
export const ACTION_FORM_SET = 'ACTION_FORM_SET'
export const ACTION_FORM_SAVE = 'ACTION_FORM_SAVE'
export const ACTION_FORM_REFRESH = 'ACTION_FORM_REFRESH'
export const ACTION_FORM_CLEAR = 'ACTION_FORM_CLEAR'

export const ACTION_UI_SET_SIZE = 'ACTION_UI_SET_SIZE'

export const ACTION_SET_EXCEPTION = 'ACTION_SET_EXCEPTION'

export const ACTION_SET_NOTIFICATION = 'ACTION_SET_NOTIFICATION'
